### ISSUE TITLE
photos?

### ISSUE THREAD

**Issue by techieshark** [rickerbh/GenerativeArtHaskell#1]
> If you'd like to tidy it, or suggest better ways to do things please do via issues/pull reqeusts.

Do you have any photos from the output? I'd love to see a couple in the README (or just here on this issue). 

Thanks!

**Comment by rickerbh** [comment]
Hey - sorry for the delay in reply - github notifications didn't seem to alert me about this issue. I've attached a couple of images from the playground. I've created/joined together a small collection of functions (sine/cosine wave generator, perlin noise generator, simplex noise generator), and applied them to other generators such as circle and spiral generators. I've attached some images of what these produce. I've love to find more time to work on this, but it's tricky.

<img width="522" alt="screen shot 2016-03-24 at 12 55 56 pm" src="https://cloud.githubusercontent.com/assets/18548/14006446/69675530-f1c1-11e5-98db-d25b97274d63.png">

<img width="111" alt="screen shot 2016-03-24 at 1 07 21 pm" src="https://cloud.githubusercontent.com/assets/18548/14006448/70eb677e-f1c1-11e5-8b9d-3e45eac50812.png">

<img width="513" alt="screen shot 2016-03-24 at 12 56 11 pm" src="https://cloud.githubusercontent.com/assets/18548/14006452/77f4088c-f1c1-11e5-8579-c7101f640950.png">

<img width="531" alt="screen shot 2016-03-24 at 12 55 41 pm" src="https://cloud.githubusercontent.com/assets/18548/14006453/7beb3d34-f1c1-11e5-9273-85e9e18e01e5.png">

**Comment by techieshark** [comment]
Ah, awesome! Thanks!
